version: '2'

services:
  nfs:
   image: 'hdac/tokenswap:nfsserver_0618'
   stdin_open: true
   privileged: true
   tty: true
   network_mode: "host"
   volumes:
    - /opt/shareLib:/opt/shareLib
   container_name: nfsserver
   working_dir: /opt
   command: init
   
