version: '2'

services:
  webserver2:
   image: 'hdac/bridgenode:webserver_v09'
   stdin_open: true
   privileged: true
   tty: true
   volumes:
    - lib-share:/opt/shareLib:rw
   network_mode: "host"
   container_name: webserver
   working_dir: /opt
   command: init

volumes:
 lib-share:
  driver: local
  driver_opts:
    type: nfs
    o: "addr=127.0.0.1,rw"
    device: ":/opt/shareLib"


